### PR TITLE
Peiqi

### PR DESCRIPTION
**Pull request by peiqi-liu**

### CODE REVIEW

**Comment by Michedev** [comment]
Thank you for reminding me to fix the project! I will merge the changes very soon

**Comment by peiqi-liu** [comment]
Sorry. I am trying to apply this model to another dataset as my course project. I think this github repo is a good place to start so I forked it. When I created pull request I did not check the branch carefully. All these changes are just my personal experiment so feel free to ignore it. Sorry again.

**Comment by peiqi-liu** [comment]
But here is one real "problem" when I run it myself which is on https://github.com/Michedev/DDPMs-Pytorch/blob/master/model/unet_class.py#L91 .  t is usually a vector of size (batch_size), and I think this might cause the matrix multiplication shape error. You might consider to reshape it into (batch_size, 1). (This problem occurs on my friend's and my training but I am not certain whether this is same for you.)

**Comment by Michedev** [comment]
I trained the model with this code so I am pretty sure that works but there could be a bug or a code error. Can you do an issue describing the problem with a code example?

**Pull request closed without merging**
